return {
  {
    id = "edit_word_tail",
    category = "edit",
    title = "cw：只修改变量名后半段",
    kind = "edit",
    filetype = "javascript",
    task = "把 cache_old 改成 cache_new，保留 cache_ 前缀。",
    hint = "光标在 old 的 o 上。按 cw，输入 new，再按 Esc；cw 从光标处改到词尾。",
    lines = { "const cache_old = source;" },
    target = { "const cache_new = source;" },
    start = { 1, 12 },
  },
  {
    id = "edit_replace_character",
    category = "edit",
    title = "r：替换一个字符",
    kind = "edit",
    filetype = "javascript",
    task = "把 count > limit 改成 count < limit，其他内容不变。",
    hint = "光标在 > 上。按 r，再输入 <；r 替换一个字符，不进入持续插入模式。",
    lines = { "if (count > limit) return;" },
    target = { "if (count < limit) return;" },
    start = { 1, 10 },
  },
  {
    id = "edit_transpose_letters",
    category = "edit",
    title = "xp：交换相邻字符",
    kind = "edit",
    filetype = "javascript",
    task = "把拼错的 vlaue 修正为 value。",
    hint = "光标在 l 上。x 删除 l，p 把它放到后面的 a 之后。",
    lines = { "return vlaue;" },
    target = { "return value;" },
    start = { 1, 8 },
  },
  {
    id = "edit_expand_operator",
    category = "edit",
    title = "s：把一个字符换成多个字符",
    kind = "edit",
    filetype = "javascript",
    task = "把 index > size 改成 index >= size。",
    hint = "光标在 > 上。按 s 删除它并进入插入模式，输入 >=，再按 Esc。",
    lines = { "if (index > size) return error;" },
    target = { "if (index >= size) return error;" },
    start = { 1, 10 },
  },
  {
    id = "edit_change_until_comma",
    category = "edit",
    title = "ct,：替换一段参数表达式",
    kind = "edit",
    filetype = "javascript",
    task = "把第一个参数 old_value + offset 改成 payload，保留逗号和第二个参数。",
    hint = "光标在 old_value 词首。按 ct,，输入 payload，再按 Esc；t, 不包含逗号。",
    lines = { "send(old_value + offset, retries);" },
    target = { "send(payload, retries);" },
    start = { 1, 5 },
  },
  {
    id = "edit_delete_through_comma",
    category = "edit",
    title = "df,：连同分隔符一起删除",
    kind = "edit",
    filetype = "javascript",
    task = "删除中间参数 legacy_mode 及它后面的逗号，剩下 payload 和 timeout。",
    hint = "光标在 legacy_mode 前的空格上。按 df,，删除到下一个逗号（包含逗号）。",
    lines = { "send(payload, legacy_mode, timeout);" },
    target = { "send(payload, timeout);" },
    start = { 1, 13 },
  },
  {
    id = "edit_replace_line_tail",
    category = "edit",
    title = "C：重写赋值表达式",
    kind = "edit",
    filetype = "javascript",
    task = "把等号右边的整个表达式改成 5000，保留分号。",
    hint = "光标在 config 上。按 C，输入 5000;，再按 Esc；C 等同于 c$。",
    lines = { "const timeout = config.timeout || 3000;" },
    target = { "const timeout = 5000;" },
    start = { 1, 16 },
  },
  {
    id = "edit_remove_trailing_comment",
    category = "edit",
    title = "D：删掉行尾注释",
    kind = "edit",
    filetype = "javascript",
    task = "删除分号之后的空格与临时注释，保留代码和分号。",
    hint = "光标在分号后的空格上。按 D 删除到行尾；D 等同于 d$。",
    lines = { "const count = items.length; // temporary log" },
    target = { "const count = items.length;" },
    start = { 1, 27 },
  },
  {
    id = "edit_replace_statement",
    category = "edit",
    title = "cc：替换一整行语句",
    kind = "edit",
    filetype = "javascript",
    task = "把中间的调试语句改成 publish(value);，保留前后两行。",
    hint = "光标在中间一行。按 cc，输入 publish(value);，再按 Esc。",
    lines = { "prepare();", "debug_log(value);", "finish();" },
    target = { "prepare();", "publish(value);", "finish();" },
    start = { 2, 0 },
  },
  {
    id = "edit_replace_counted_chars",
    category = "edit",
    title = "3s：精确修改三个字符",
    kind = "edit",
    filetype = "javascript",
    task = "把文案中的 DEV 改成 REL，保留后面的空格和 build。",
    hint = "光标在 D 上。按 3s，输入 REL，再按 Esc；数字限制删除的字符数。",
    lines = { "const label = \"DEV build\";" },
    target = { "const label = \"REL build\";" },
    start = { 1, 15 },
  },
  {
    id = "edit_repeat_word_change",
    category = "edit",
    title = "点命令：重复一次局部修改",
    kind = "edit",
    filetype = "javascript",
    task = "把两行里的 old_value 都改成 new_value。",
    hint = "先 cw 输入 new_value 并按 Esc；再 /old_value 回车定位第二处，按 . 重复修改。",
    lines = { "const first = old_value;", "const second = old_value;" },
    target = { "const first = new_value;", "const second = new_value;" },
    start = { 1, 14 },
  },
  {
    id = "edit_substitute_current_line",
    category = "edit",
    title = "只替换当前行的多处匹配",
    kind = "edit",
    filetype = "javascript",
    task = "仅把第一行的两个 old 改成 new，第二行保持原样。",
    hint = "输入 :s/old/new/g 并回车。没有 % 就只处理当前行；g 表示处理这一行所有匹配。",
    lines = { "send(old, old);", "send(old, keep);" },
    target = { "send(new, new);", "send(old, keep);" },
    start = { 1, 5 },
  },
  {
    id = "object_inner_word_middle",
    category = "objects",
    title = "ciw：从词中间修改整词",
    kind = "edit",
    filetype = "javascript",
    task = "把 cached_value 整体改成 result，保留 return 和分号。",
    hint = "光标在 value 的 v 上。按 ciw，输入 result，再按 Esc；iw 会包含光标前的 cached_。",
    lines = { "return cached_value;" },
    target = { "return result;" },
    start = { 1, 14 },
  },
  {
    id = "object_around_word_space",
    category = "objects",
    title = "daw：删除单词及相邻空格",
    kind = "edit",
    filetype = "text",
    task = "删除 obsolete，让 Deploy 与 workers 之间只留一个空格。",
    hint = "光标在 obsolete 中。按 daw；aw 包含单词与相邻空白，避免删除后留下双空格。",
    lines = { "Deploy obsolete workers now." },
    target = { "Deploy workers now." },
    start = { 1, 10 },
  },
  {
    id = "object_big_word_url",
    category = "objects",
    title = "ciW：整体修改 URL",
    kind = "edit",
    filetype = "sh",
    task = "把 URL 换成 https://api.example/v2，保留 curl 和 --silent。",
    hint = "光标在旧域名中。按 ciW 输入新 URL，再按 Esc；W 只按空白分隔，包含点和斜杠。",
    lines = { "curl https://old.example/v1 --silent" },
    target = { "curl https://api.example/v2 --silent" },
    start = { 1, 13 },
  },
  {
    id = "object_single_quote_content",
    category = "objects",
    title = "ci'：保留单引号",
    kind = "edit",
    filetype = "javascript",
    task = "把 development 改成 production，保留单引号和分号。",
    hint = "光标在字符串里。按 ci'，输入 production，再按 Esc。",
    lines = { "const mode = 'development';" },
    target = { "const mode = 'production';" },
    start = { 1, 18 },
  },
  {
    id = "object_around_quote_expression",
    category = "objects",
    title = "ca\"：把字符串改成布尔值",
    kind = "edit",
    filetype = "javascript",
    task = "把带引号的 \"true\" 改成不带引号的 true。",
    hint = "按 ca\" 后输入一个空格和 true，再按 Esc。本题 a\" 也会带走引号前的空格。",
    lines = { "const enabled = \"true\";" },
    target = { "const enabled = true;" },
    start = { 1, 17 },
  },
  {
    id = "object_backtick_command",
    category = "objects",
    title = "反引号里的命令",
    kind = "edit",
    filetype = "markdown",
    task = "只把行内命令改为 npm install new-tool，保留两边反引号。",
    hint = "光标在命令中。按 ci`，输入 npm install new-tool，再按 Esc。",
    lines = { "Run `npm install old-tool` today." },
    target = { "Run `npm install new-tool` today." },
    start = { 1, 17 },
  },
  {
    id = "object_inner_nested_parens",
    category = "objects",
    title = "cib：只改内层括号",
    kind = "edit",
    filetype = "javascript",
    task = "把 normalize 的参数改为 payload，保留外层 send 的 retries 参数。",
    hint = "光标在 raw 上。按 cib，输入 payload，再按 Esc；ib 等同于 i(，选择包住光标的内层括号。",
    lines = { "send(normalize(raw, flags), retries);" },
    target = { "send(normalize(payload), retries);" },
    start = { 1, 15 },
  },
  {
    id = "object_around_parens",
    category = "objects",
    title = "dab：包含整对圆括号",
    kind = "edit",
    filetype = "markdown",
    task = "把文档中的 render(options) 简写成 render，删掉参数和整对括号。",
    hint = "光标在 options 中。按 dab；ab 等同于 a(，会包含左右括号。",
    lines = { "Search for render(options) in the docs." },
    target = { "Search for render in the docs." },
    start = { 1, 20 },
  },
  {
    id = "object_inner_brackets",
    category = "objects",
    title = "ci[：修改数组内容",
    kind = "edit",
    filetype = "javascript",
    task = "把数组内容改成 2, 4, 8，保留方括号和分号。",
    hint = "光标在数组内。按 ci[，输入 2, 4, 8，再按 Esc。",
    lines = { "const retries = [1, 2, 3];" },
    target = { "const retries = [2, 4, 8];" },
    start = { 1, 17 },
  },
  {
    id = "object_around_brackets",
    category = "objects",
    title = "da[：删除索引访问",
    kind = "edit",
    filetype = "javascript",
    task = "把 labels[index] 改成 labels，保留赋值语句。",
    hint = "光标在 index 上。按 da[，把索引和整对方括号一起删除。",
    lines = { "const label = labels[index];" },
    target = { "const label = labels;" },
    start = { 1, 21 },
  },
  {
    id = "object_inner_braces",
    category = "objects",
    title = "ciB：替换对象内部",
    kind = "edit",
    filetype = "javascript",
    task = "把对象内容改成 retries: 3，保留花括号；括号内两侧各留一个空格。",
    hint = "光标在 debug 上。按 ciB，输入空格、retries: 3、空格，再按 Esc；iB 等同于 i{。",
    lines = { "const options = { debug: true, retries: 1 };" },
    target = { "const options = { retries: 3 };" },
    start = { 1, 18 },
  },
  {
    id = "object_inner_nested_tag",
    category = "objects",
    title = "cit：保留内外两层标签",
    kind = "edit",
    filetype = "html",
    task = "只把 Draft 改成 Ready，保留 strong 和 section 两层标签。",
    hint = "光标在 Draft 中。按 cit，输入 Ready，再按 Esc；it 选择当前内层标签的内容。",
    lines = { "<section><strong>Draft</strong></section>" },
    target = { "<section><strong>Ready</strong></section>" },
    start = { 1, 17 },
  },
  {
    id = "object_around_nested_tag",
    category = "objects",
    title = "dat：删除整段标签",
    kind = "edit",
    filetype = "html",
    task = "删除整个 span 标签及 temporary 文本，保留 div 与 b 标签。",
    hint = "光标在 temporary 中。按 dat；at 包含当前标签的起止标签及内容。",
    lines = { "<div><span>temporary</span><b>Ready</b></div>" },
    target = { "<div><b>Ready</b></div>" },
    start = { 1, 11 },
  },
  {
    id = "object_change_paragraph",
    category = "objects",
    title = "cip：整段重写",
    kind = "edit",
    filetype = "markdown",
    task = "把过时的两行段落换成 Write a regression test.，保留标题、后续段落和空行。",
    hint = "光标在过时段落内。按 cip，输入 Write a regression test.，再按 Esc；ip 选择整个段落。",
    lines = { "Notes", "", "Outdated paragraph.", "Do not follow this.", "", "Next steps." },
    target = { "Notes", "", "Write a regression test.", "", "Next steps." },
    start = { 3, 0 },
  },
  {
    id = "object_inner_sentence",
    category = "objects",
    title = "cis：修改当前句子",
    kind = "edit",
    filetype = "text",
    task = "只把第一句改成 Cache is fresh.，保留第二句和句间两个空格。",
    hint = "光标在 stale 中。按 cis，输入 Cache is fresh.，再按 Esc；is 不包含句后空白。",
    lines = { "Cache is stale.  Retry is safe." },
    target = { "Cache is fresh.  Retry is safe." },
    start = { 1, 9 },
  },
  {
    id = "object_around_sentence",
    category = "objects",
    title = "das：连同句间空白删除",
    kind = "edit",
    filetype = "text",
    task = "删除第一句 Cache is stale. 及其后空白，让 Retry 成为行首。",
    hint = "光标在第一句内。按 das；as 包含句子和相邻空白。",
    lines = { "Cache is stale.  Retry is safe." },
    target = { "Retry is safe." },
    start = { 1, 9 },
  },
}
