"""Run with python3 tests/test_ui.py [plugin-root] [init.lua]. No Python dependencies."""
import sys
sys.dont_write_bytecode = True
from ui_driver import Nvim
import pathlib

root = sys.argv[1] if len(sys.argv) > 1 else str(next(p for p in pathlib.Path(__file__).resolve().parents if (p / 'plugin/vim_practice.lua').exists()))
init = sys.argv[2] if len(sys.argv) > 2 else 'NONE'
n = Nvim(root, init=init)
checks = []

def check(condition, label):
    if not condition:
        print(n.screen())
        print(n.state())
        raise AssertionError(label)
    checks.append(label)

def start(category, offset=0):
    n.command('VimPractice ' + category)
    if n.state()['auto']: n.keys('<F9>')
    for _ in range(offset): n.keys('<F8>')

def passed(keys, label):
    n.keys(keys)
    check(n.state().get('passed'), label)

try:
    # Load insert-time plugins before entering practice, then preserve this draft.
    n.command('enew')
    n.keys('iUser draft<Esc>')
    n.keys('A kept<Esc>')
    original = n.lua('return {vim.api.nvim_get_current_tabpage(),vim.api.nvim_get_current_buf()}')
    n.lua("vim.fn.setreg('a','KEEP_REGISTER'); vim.fn.setreg('0','KEEP_ZERO')")
    n.command('VimPractice')
    check('选择专题' in n.screen() and not n.state().get('id'), 'dashboard opens before practice')
    n.keys('<CR>')
    check(n.state()['id'] == 'basic_hjkl', 'Enter starts selected topic')
    n.keys('<F4>')
    check(not n.state().get('id'), 'F4 returns to dashboard')

    start('edit')
    n.keys('<F9>')
    n.keys('ci"Connection lost', wait=.35)
    check(n.state()['id'] == 'change_string' and not n.state()['passed'], 'insert mode never changes lesson')
    n.keys('<Esc>', wait=.35)
    check(n.state()['id'] == 'fix_identifier', 'real edit automatically advances')
    n.keys('<F9>')
    passed(':%s/user_nmae/user_name/g<CR>', 'global replacement')
    n.keys('<F5>')
    check(not n.state()['passed'], 'retry resets completion')
    n.keys('u')
    check(n.lua('return vim.api.nvim_buf_get_lines(0,0,-1,false)') == ['const auto user_nmae = request.user_name();','log_user(user_nmae);'], 'retry undo cannot expose prior lesson')

    start('edit')
    n.keys('<F9>')
    n.keys('ci"Connection lost<Esc>', wait=.02)
    n.keys('<C-w>w', wait=.25)
    check(n.state()['id'] == 'change_string', 'auto advance waits while reading guide')
    n.keys('q', wait=.3)
    check(n.state()['id'] == 'fix_identifier', 'auto advance resumes after returning to editor')
    start('edit')
    if not n.state()['auto']: n.keys('<F9>')
    n.keys('ci"Connection lost<Esc>', wait=.02)
    n.keys('u', wait=.3)
    check(n.state()['id'] == 'change_string' and not n.state()['passed'], 'changing completed content cancels pending advance')

    start('edit', 1)
    n.keys('<F7>')
    check(n.state()['id'] == 'change_string', 'F7 returns to previous lesson')
    check(not n.state()['passed'] and 'Connection failed' in n.lua('return vim.api.nvim_get_current_line()'), 'previous lesson starts with original content')
    n.keys('<F7>')
    check(n.state()['index'] == 1 and '第一题' in n.state()['status'], 'previous at first lesson stays in place')
    n.keys('<F8>')
    n.command('VimPracticePrev')
    check(n.state()['id'] == 'change_string', 'previous command matches shortcut')
    n.keys('<F8>')
    n.keys('<F9>')
    n.keys(':%s/user_nmae/user_name/g<CR>', wait=.02)
    n.keys('<F7>', wait=.3)
    check(n.state()['id'] == 'change_string', 'previous cancels pending automatic advance')

    start('basics')
    passed('2j2l', 'movement target')
    start('navigate')
    passed('/TODO<CR>', 'search target')
    start('objects', 2)
    passed('di(', 'native text object')
    start('visual', 3)
    passed('gg0<C-v>2jI// <Esc>', 'blockwise insertion')
    start('registers', 4)
    passed('gg"ayy2j"AyyG"ap', 'named register append and paste')
    start('automation', 1)
    n.keys('ggqaA;<Esc>jq')
    check(n.lua("return vim.fn.keytrans(vim.fn.getreg('a'))") == 'A;<Esc>j', 'macro is recorded intact after completion plugins load')
    passed('3@a', 'macro recording and replay without q interception')
    start('history')
    n.keys('$x')
    check(n.state()['stage'] == 2, 'history advances to explicit undo step')
    passed('u', 'real undo accepted')
    start('history', 1)
    n.keys('gg0ciwreturn<Esc>')
    check(n.state()['stage'] == 2, 'history redo editing stage')
    n.keys('u')
    check(n.state()['stage'] == 3, 'history undo stage')
    passed('<C-r>', 'real redo accepted')
    start('folds')
    passed('2GV2jzf', 'create fold')
    for offset, key in [(1,'zo'),(2,'zc'),(3,'zM'),(4,'zR')]:
        start('folds', offset)
        passed(key, 'fold action ' + key)
    start('files')
    n.keys('ciwnew<Esc>')
    check(not n.state()['passed'], 'file content alone is insufficient')
    passed(':w<CR>', 'file write verified on disk')
    start('files', 1)
    n.keys(':e!<CR>')
    check(not n.state()['passed'], 'reload without edit rejected')
    n.keys('gg$ciwwrong<Esc>')
    passed(':e!<CR>', 'reload after actual unsaved edit')
    start('files', 2)
    temporary_path = n.lua('return vim.api.nvim_buf_get_name(0)')
    n.keys('ciwnew<Esc>')
    passed(':saveas %:r-copy.txt<CR>', 'save as verified on disk')
    n.keys('<F4>')
    check(not n.lua('for _,b in ipairs(vim.api.nvim_list_bufs()) do if vim.api.nvim_buf_get_name(b)==... then return true end end; return false', temporary_path), 'saveas alternate buffer cleaned up')
    for offset, key in [(0,':split<CR>'),(1,':vsplit<CR>'),(2,'<C-w>w'),(3,':enew<CR>'),(4,':b#<CR>'),(5,':tabnew<CR>')]:
        start('workspace', offset)
        passed(key, 'workspace action ' + key)

    start('edit')
    n.call('nvim_ui_try_resize', 80, 24)
    n.pump(.1)
    screen = n.screen()
    check('local message' in screen and 'notify(message)' in screen, 'resize shows complete short source lines')
    check('目标内容' in screen and 'Connection lost' in screen and 'F9 自动' in screen and '在这里操作' in screen, '80x24 shows instructions target controls and editor')
    start('registers', 1)
    check('7  }' in n.screen(), '80x24 long target remains visible')
    n.call('nvim_ui_try_resize', 120, 36)
    n.pump(.1)
    check('目标内容' in n.screen(), 'resize restores wide layout')

    # An unrelated tab created while practising must survive cleanup.
    start('edit')
    n.command('tabnew')
    foreign_tab = n.lua('return vim.api.nvim_get_current_tabpage()')
    n.keys('iDO NOT DISCARD<Esc>')
    foreign_buf = n.lua('return vim.api.nvim_get_current_buf()')
    n.command('VimPracticeStop')
    check(n.lua('return vim.api.nvim_tabpage_is_valid(...)', foreign_tab), 'unrelated tab preserved')
    check(n.lua('return vim.api.nvim_buf_get_lines(...,0,-1,false)', foreign_buf) == ['DO NOT DISCARD'], 'unrelated unsaved text preserved')
    check(n.lua('return vim.api.nvim_get_current_tabpage()') == original[0], 'exit returns to original tab')
    check(n.lua('return vim.api.nvim_buf_get_lines(...,0,-1,false)', original[1]) == ['User draft kept'], 'original unsaved draft preserved')
    check(n.lua("return vim.fn.getreg('a')") == 'KEEP_REGISTER', 'named register restored')
    check(n.lua("return vim.fn.getreg('0')") == 'KEEP_ZERO', 'yank register restored')
    check(n.lua("return vim.fn.exists(':VimPractice2')") == 0, 'legacy command absent')
    check(n.lua("return vim.fn.exists('#VimPracticeWorkbench')") == 0, 'session callbacks removed')
    print(f'PASS: {len(checks)} real-input and screen checks')
finally:
    n.close()
