" GENERATED by resources/editors/generate.py — Otty config filetype detection.
" The file is named config.toml but is Ghostty-style key=value, not real TOML,
" so we override TOML detection for the otty config path specifically.
augroup ottyConfig
  autocmd!
  autocmd BufRead,BufNewFile */otty/config,*/otty/config.toml,*/otty-debug/config,*/otty-debug/config.toml
        \ setlocal filetype=otty
augroup END
